### ISSUE TITLE
Carte MFU : modification du titre

### ISSUE THREAD

**Issue by tomgachet** [CEN-Nouvelle-Aquitaine/map_cen#5]
Pour plus de lisibilité, je propose de modifier le titre de la carte comme cela :

- _Nom du site_ _(département)_ : Maîtrise foncière ou d'usage au _date d'édition_
Pas besoin de mettre site car on a l'info dans le sous titre
On rajoute la date dans le titre

**Comment by wanderzen91** [comment]
Ok par contre faut que je remplace "Maîtrise foncière ou d'usage" par "MFU" sinon le titre va être trop long pour de nombreux sites !

**Comment by tomgachet** [comment]
Pas très fan d'utiliser un acronyme en titre..
Et pourquoi pas présenter comme ça? :

**Nom du site (dpt)**
Sous-titre : Maîtrise foncière ou d'usage au _date d'édition_

Et mettre la surface totale maîtrisée entre la légende et la carte de situation?

**Comment by wanderzen91** [comment]
Testé à l'instant et c'est carrément mieux, je push les modif' avec une montée en version
