### ISSUE TITLE
Carte MFU : Gestion de la barre d'échelle 

### ISSUE THREAD

**Issue by tomgachet** [CEN-Nouvelle-Aquitaine/map_cen#6]
Actuellement la barre d'échelle s'adapte au zoom de la carte mais avec des tailles différentes.
Il faudrait que la taille de la barre soit fixe (2 cm par exemple) et que seules les unités changent. 
A voir aussi pour un paramétrage d'échelle (pour ne pas avoir des unités farfelues)

**Comment by wanderzen91** [comment]
J'avais noté le bug avec le changement d'échelle, je vais regarder cette aprem comment fixer la taille de la barre avec une adaptation de l'échelle automatique au niveau de zoom
